### ISSUE TITLE
Source code string can not contain null bytes

### ISSUE THREAD

**Issue by raffoul** [llamafilm/tesla-http-proxy-addon#88]
### The problem

Hello,
I've updated home assistant to 2024.5.0.

I have the following issue : SyntaxError: source code string cannot contain null bytes

I'm not sure this is the update. What do you think about this ?

Thanks for your help

### What version of the addon are you using?

2.2.3

### What version of Home Assistant Core are you using?

core-2024.5.0

### What type of installation are you running?

Home Assistant OS

### What version of Tesla integration are you using?

3.21.0

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y - 2023

### What is your domain name (FQDN)?

tesla.limbach.fr

### Paste the log output from the addon here

```text
s6-rc: info: service webui successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service webui: starting
s6-rc: info: service webui successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/app/webui.py", line 6, in <module>
    from flask import cli, Flask, render_template, request
  File "/usr/lib/python3.11/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/lib/python3.11/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/lib/python3.11/site-packages/flask/globals.py", line 4, in <module>
    from werkzeug.local import LocalProxy
  File "/usr/lib/python3.11/site-packages/werkzeug/__init__.py", line 1, in <module>
    from .serving import run_simple as run_simple
  File "/usr/lib/python3.11/site-packages/werkzeug/serving.py", line 35, in <module>
    from .urls import uri_to_iri
  File "/usr/lib/python3.11/site-packages/werkzeug/urls.py", line 23, in <module>
    from .datastructures import iter_multi_items
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/__init__.py", line 1, in <module>
    from .accept import Accept as Accept
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/accept.py", line 6, in <module>
    from .structures import ImmutableList
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 1006, in <module>
    from .. import http
  File "/usr/lib/python3.11/site-packages/werkzeug/http.py", line 18, in <module>
    from urllib.request import parse_http_list as _parse_list_header
SyntaxError: source code string cannot contain null bytes
[05:53:30] INFO: Found existing keypair
[05:53:30] INFO: Testing public key...
[05:53:30] FATAL: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service webui: stopping
s6-rc: info: service webui successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service webui: starting
s6-rc: info: service webui successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/app/webui.py", line 6, in <module>
    from flask import cli, Flask, render_template, request
  File "/usr/lib/python3.11/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/lib/python3.11/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/lib/python3.11/site-packages/flask/globals.py", line 4, in <module>
    from werkzeug.local import LocalProxy
  File "/usr/lib/python3.11/site-packages/werkzeug/__init__.py", line 1, in <module>
    from .serving import run_simple as run_simple
  File "/usr/lib/python3.11/site-packages/werkzeug/serving.py", line 35, in <module>
    from .urls import uri_to_iri
  File "/usr/lib/python3.11/site-packages/werkzeug/urls.py", line 23, in <module>
    from .datastructures import iter_multi_items
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/__init__.py", line 1, in <module>
    from .accept import Accept as Accept
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/accept.py", line 6, in <module>
    from .structures import ImmutableList
  File "/usr/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 1006, in <module>
    from .. import http
  File "/usr/lib/python3.11/site-packages/werkzeug/http.py", line 18, in <module>
    from urllib.request import parse_http_list as _parse_list_header
SyntaxError: source code string cannot contain null bytes
[05:53:42] INFO: Found existing keypair
[05:53:42] INFO: Testing public key...
[05:53:42] FATAL: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service webui: stopping
s6-rc: info: service webui successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by llamafilm** [comment]
I have no problems with 2024.5.0.  This looks like an error during installation, or maybe a corrupt file on disk.  Can you try restoring to the most recent working HA core backup?  If that works, then try upgrading again.

**Comment by raffoul** [comment]
Finally, a full restart resolve the issue and now the proxy is running with the previous error. I don't know the root cause.
Thank you.
